version: "3.5"

services:
  mysql:
    image: "docker.io/bitnami/mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/bitnami/mysql/data"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MYSQL_DATABASE=flex-home
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    networks:
      - mysqlnet

networks:
  mysqlnet:
    external:
      name: mysql_network

volumes:
  mysql_data:
    driver: local
